### PR TITLE
Add support for flake.nix and shell.nix

### PR DESCRIPTION
**Pull request by flogth**
Hi, this patch adds support for nix flakes and shell.nix files.
These are both similar in nature to guix manifest files. Flakes are the new and shiny implementation, but as both flakes and shell.nix files seem to be used equally in the nix community, I think it makes sense to support both.

### CODE REVIEW

**Comment by astoff** [comment]
Nice, thanks for the suggestion.

Can you briefly explain what the difference is between these two files? Are both widely used, and could them perhaps be handled in a unified way? Obviously, I'd always prefer to handle the smallest possible number of cases.

**Comment by flogth** [comment]
A `shell.nix` file is a file written in the Nix language that happens to evaluate to a development shell. Naming the file shell.nix is just a convention, although a very common one. Most older projects use this.

[Flakes](https://nixos.wiki/wiki/Flakes) are a newer development aiming to standardize the way nix projects are composed. They also allow things like enforcing pure evaluation or pinning versions of dependencies. With that comes a new set of cli utilities, which have to be used here. At the moment flakes still have to be enabled with an experimental flag, though that doesn't stop a big chunk of the nix community (including myself) from using them.

So unfortunately these have to be handled separately.

**Comment by astoff** [comment]
> Naming the file shell.nix is just a convention, although a very common one.

Does it make sense to catch `"*.nix"` instead of `"shell.nix"`, or would this just create confusion?

**Comment by flogth** [comment]
> Does it make sense to catch "*.nix" instead of "shell.nix", or would this just create confusion?

I don't think it does, as the command only works with nix files that provide a dev shell. Most will not, so catching them seems counterintuitive to me.

**Comment by astoff** [comment]
Okay, thanks for the clarifications!

**Pull request merged**
